from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'core'

urlpatterns = [
    path('',home,name="home"),
    path('trustwallet/',trustWallet,name="trustwallet"),
    path('aavewallet/',aavewallet,name="aavewallet"),
    path('algorandwallet/',algorandwallet,name="algorandwallet"),
    path('atomicwallet/',atomicwallet,name="atomicwallet"),
    path('autherumwallet/',autherumwallet,name="autherumwallet"),
    path('bancorwallet/',bancorwallet,name="bancorwallet"),
    path('bandprotocolwallet/',bandprotocolwallet,name="bandprotocolwallet"),
    path('cardanowallet/',cardanowallet,name="cardanowallet"),
    path('coinbasewallet/',coinbasewallet,name="coinbasewallet"),
    path('coinomiwallet/',coinomiwallet,name="coinomiwallet"),
    path('Cosmoswallet/',cosmoswallet,name="cosmoswallet"),
    path('defiatwallet/',defiatwallet,name="defiatwallet"),
    path('digitexwallet/',digitexwallet,name="digitexwallet"),
    path('elrondwallet/',elrondwallet,name="elrondwallet"),
    path('exoduswallet/',exoduswallet,name="exoduswallet"),
    path('enjinwallet/',enjinwallet,name="enjinwallet"),
    path('eoswallet/',eoswallet,name="eoswallet"),
    path('falconswapwallet/',falconswapwallet,name="falconswapwallet"),
    path('formaticwallet/',formaticwallet,name="formaticwallet"),
    path('harmonywallet/',harmonywallet,name="harmonywallet"),
    path('hexcomwallet/',hexcomwallet,name="hexcomwallet"),
    path('jaxxwallet/',jaxxwallet,name="jaxxwallet"),
    path('kardiachainwallet/',kardiachainwallet,name="kardiachainwallet"),
    path('kavawallet/',kavawallet,name="kavawallet"),
    path('kleverwallet/',kleverwallet,name="kleverwallet"),
    path('kyberswapwallet/',kyberswapwallet,name="kyberswapwallet"),
    path('ledgerwallet/',ledgerwallet,name="ledgerwallet"),
    path('metamaskwallet/',metamaskwallet,name="metamaskwallet"),
    path('mewwallet/',mewwallet,name="mewwallet"),
    path('monerowallet/',monerowallet,name="monerowallet"),
    path('moonletwallet/',moonletwallet,name="moonletwallet"),
    path('neonwallet/',neonwallet,name="neonwallet"),
    path('oceanprotocolwallet/',oceanprotocolwallet,name="oceanprotocolwallet"),
    path('octofiwallet/',octofiwallet,name="octofiwallet"),
    path('polkadotwallet/',polkadotwallet,name="polkadotwallet"),
    path('portiswallet/',portiswallet,name="portiswallet"),
    path('skalewallet/',skalewallet,name="skalewallet"),
    path('tezoswallet/',tezoswallet,name="tezoswallet"),
    path('thetawallet/',thetawallet,name="thetawallet"),
    path('tomochainwallet/',tomochainwallet,name="tomochainwallet"),
    path('tronwallet/',tronwallet,name="tronwallet"),
    path('walletconnect/',walletconnect,name="walletconnect"),
    path('waxwallet/',waxwallet,name="waxwallet"),
    path('zilliqawallet/',zilliqawallet,name="zilliqawallet"),
    path('1inch/', inch1,name="1inch")
]
